# Generated by Django 5.1.3 on 2025-08-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usersurname',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
