# Generated by Django 5.1.3 on 2025-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_usersurname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='usersurname',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
