# Generated by Django 5.1.3 on 2025-08-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_usersurname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('courier', 'Kurier'), ('client', 'Klient')], default='client', max_length=10),
        ),
    ]
