# Generated by Django 5.1.3 on 2024-11-25 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('picked_up_by_courier', 'Picked up by courier'), ('delivered_to_machine', 'Delivered to machine'), ('received_by_recipient', 'Received by recipient')], default='sent', max_length=50)),
                ('size', models.CharField(choices=[('small', 'Small'), ('large', 'Large')], default='small', max_length=6)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('courier_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sent_from_machine', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_to_machine', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_parcels', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_parcels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
