# Generated by Django 5.1.3 on 2024-11-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('shipment_ordered', 'Shipment ordered'), ('stored_in_machine', 'Stored in machine'), ('picked_up_by_courier', 'Picked up by courier'), ('delivered_to_machine', 'Delivered to machine'), ('received_by_recipient', 'Received by recipient')], default='shipment_ordered', max_length=50)),
                ('package_size', models.CharField(choices=[('small', 'Small'), ('large', 'Large')], default='small', max_length=6)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('courier_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
