# Generated by Django 5.1.3 on 2024-11-25 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='size',
            new_name='package_size',
        ),
    ]
