# Generated by Django 5.1.3 on 2024-11-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_rename_size_parcel_package_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('shipment_ordered', 'Shipment ordered'), ('stored_in_machine', 'Stored in machine'), ('picked_up_by_courier', 'Picked up by courier'), ('delivered_to_machine', 'Delivered to machine'), ('received_by_recipient', 'Received by recipient')], default='sent', max_length=50),
        ),
    ]
