# Generated by Django 5.1.3 on 2025-08-26 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='package_size',
            field=models.CharField(choices=[('small', 'Mała'), ('large', 'Duża')], default='small', max_length=6),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('shipment_ordered', 'Przesyłka zamówiona'), ('stored_in_machine', 'Umieszona w skrytce'), ('picked_up_by_courier', 'Odebrana przez kuriera'), ('delivered_to_machine', 'Dostarczona do skrytki docelowej'), ('received_by_recipient', 'Odebrana przez odbiorcę')], default='shipment_ordered', max_length=50),
        ),
        migrations.CreateModel(
            name='ParcelCourierHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('pickup', 'Odebrał z automatu'), ('dropoff', 'Zostawił w automacie')], max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handled_parcels', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_history', to='parcels.parcel')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
