# Generated by Django 5.1.3 on 2024-11-28 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_remove_locker_number_of_boxes_lock'),
        ('parcels', '0003_alter_parcel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='sent_from_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_parcels', to='lockers.locker'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='sent_to_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_parcels', to='lockers.locker'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('shipment_ordered', 'Shipment ordered'), ('stored_in_machine', 'Stored in machine'), ('picked_up_by_courier', 'Picked up by courier'), ('delivered_to_machine', 'Delivered to machine'), ('received_by_recipient', 'Received by recipient')], default='shipment_ordered', max_length=50),
        ),
    ]
