# Generated by Django 5.1.3 on 2025-08-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_alter_parcel_package_size_alter_parcel_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelcourierhistory',
            options={'ordering': ['-dateTime']},
        ),
        migrations.RenameField(
            model_name='parcelcourierhistory',
            old_name='at',
            new_name='dateTime',
        ),
    ]
