# Generated by Django 5.1.3 on 2024-11-28 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='number_of_boxes',
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('small', 'Small'), ('large', 'Large')], max_length=5)),
                ('is_free', models.BooleanField(default=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='lockers.locker')),
            ],
        ),
    ]
